# Generated by Django 6.1 on 2026-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
